package com.lile.common.mybits.model;

import java.math.BigDecimal;
import java.util.Date;

public class BalancePayResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.id
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.balance_no
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private String balanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private String lowLevelOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private BigDecimal sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.operator
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.id
     *
     * @return the value of balance_pay_resource.id
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.id
     *
     * @param id the value for balance_pay_resource.id
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.balance_no
     *
     * @return the value of balance_pay_resource.balance_no
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public String getBalanceNo() {
        return balanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.balance_no
     *
     * @param balanceNo the value for balance_pay_resource.balance_no
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setBalanceNo(String balanceNo) {
        this.balanceNo = balanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.low_level_org
     *
     * @return the value of balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public String getLowLevelOrg() {
        return lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.low_level_org
     *
     * @param lowLevelOrg the value for balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setLowLevelOrg(String lowLevelOrg) {
        this.lowLevelOrg = lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.sum
     *
     * @return the value of balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.sum
     *
     * @param sum the value for balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.operator
     *
     * @return the value of balance_pay_resource.operator
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.operator
     *
     * @param operator the value for balance_pay_resource.operator
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.create_time
     *
     * @return the value of balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.create_time
     *
     * @param createTime the value for balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}