package com.lile.common.mybits.model;

public class ZdBalanceResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance_resource.id
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance_resource.balance_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    private String balanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance_resource.type
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance_resource.resource_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    private String resourceNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance_resource.id
     *
     * @return the value of zd_balance_resource.id
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance_resource.id
     *
     * @param id the value for zd_balance_resource.id
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance_resource.balance_no
     *
     * @return the value of zd_balance_resource.balance_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public String getBalanceNo() {
        return balanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance_resource.balance_no
     *
     * @param balanceNo the value for zd_balance_resource.balance_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setBalanceNo(String balanceNo) {
        this.balanceNo = balanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance_resource.type
     *
     * @return the value of zd_balance_resource.type
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance_resource.type
     *
     * @param type the value for zd_balance_resource.type
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance_resource.resource_no
     *
     * @return the value of zd_balance_resource.resource_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public String getResourceNo() {
        return resourceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance_resource.resource_no
     *
     * @param resourceNo the value for zd_balance_resource.resource_no
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setResourceNo(String resourceNo) {
        this.resourceNo = resourceNo;
    }
}