package com.lile.common.mybits.model;

import java.util.ArrayList;
import java.util.List;

public class ZdBalanceResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public ZdBalanceResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBalanceNoIsNull() {
            addCriterion("balance_no is null");
            return (Criteria) this;
        }

        public Criteria andBalanceNoIsNotNull() {
            addCriterion("balance_no is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceNoEqualTo(String value) {
            addCriterion("balance_no =", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoNotEqualTo(String value) {
            addCriterion("balance_no <>", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoGreaterThan(String value) {
            addCriterion("balance_no >", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoGreaterThanOrEqualTo(String value) {
            addCriterion("balance_no >=", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoLessThan(String value) {
            addCriterion("balance_no <", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoLessThanOrEqualTo(String value) {
            addCriterion("balance_no <=", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoLike(String value) {
            addCriterion("balance_no like", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoNotLike(String value) {
            addCriterion("balance_no not like", value, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoIn(List<String> values) {
            addCriterion("balance_no in", values, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoNotIn(List<String> values) {
            addCriterion("balance_no not in", values, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoBetween(String value1, String value2) {
            addCriterion("balance_no between", value1, value2, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andBalanceNoNotBetween(String value1, String value2) {
            addCriterion("balance_no not between", value1, value2, "balanceNo");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andResourceNoIsNull() {
            addCriterion("resource_no is null");
            return (Criteria) this;
        }

        public Criteria andResourceNoIsNotNull() {
            addCriterion("resource_no is not null");
            return (Criteria) this;
        }

        public Criteria andResourceNoEqualTo(String value) {
            addCriterion("resource_no =", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoNotEqualTo(String value) {
            addCriterion("resource_no <>", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoGreaterThan(String value) {
            addCriterion("resource_no >", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoGreaterThanOrEqualTo(String value) {
            addCriterion("resource_no >=", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoLessThan(String value) {
            addCriterion("resource_no <", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoLessThanOrEqualTo(String value) {
            addCriterion("resource_no <=", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoLike(String value) {
            addCriterion("resource_no like", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoNotLike(String value) {
            addCriterion("resource_no not like", value, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoIn(List<String> values) {
            addCriterion("resource_no in", values, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoNotIn(List<String> values) {
            addCriterion("resource_no not in", values, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoBetween(String value1, String value2) {
            addCriterion("resource_no between", value1, value2, "resourceNo");
            return (Criteria) this;
        }

        public Criteria andResourceNoNotBetween(String value1, String value2) {
            addCriterion("resource_no not between", value1, value2, "resourceNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance_resource
     *
     * @mbggenerated do_not_delete_during_merge Tue May 08 23:35:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}