package com.lile.common.mybits.model;

import java.math.BigDecimal;
import java.util.Date;

public class ZdBalance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.balance_id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String balanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String highLevelOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String lowLevelOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String semesterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal publishPriceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal refundPriceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal priceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal actualTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer balanceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.id
     *
     * @return the value of zd_balance.id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.id
     *
     * @param id the value for zd_balance.id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.balance_id
     *
     * @return the value of zd_balance.balance_id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getBalanceId() {
        return balanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.balance_id
     *
     * @param balanceId the value for zd_balance.balance_id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setBalanceId(String balanceId) {
        this.balanceId = balanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.high_level_org
     *
     * @return the value of zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getHighLevelOrg() {
        return highLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.high_level_org
     *
     * @param highLevelOrg the value for zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setHighLevelOrg(String highLevelOrg) {
        this.highLevelOrg = highLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.low_level_org
     *
     * @return the value of zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getLowLevelOrg() {
        return lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.low_level_org
     *
     * @param lowLevelOrg the value for zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setLowLevelOrg(String lowLevelOrg) {
        this.lowLevelOrg = lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.semester_code
     *
     * @return the value of zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getSemesterCode() {
        return semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.semester_code
     *
     * @param semesterCode the value for zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setSemesterCode(String semesterCode) {
        this.semesterCode = semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.discount_rate
     *
     * @return the value of zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.discount_rate
     *
     * @param discountRate the value for zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.publish_price_total
     *
     * @return the value of zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getPublishPriceTotal() {
        return publishPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.publish_price_total
     *
     * @param publishPriceTotal the value for zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setPublishPriceTotal(BigDecimal publishPriceTotal) {
        this.publishPriceTotal = publishPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.refund_price_total
     *
     * @return the value of zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getRefundPriceTotal() {
        return refundPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.refund_price_total
     *
     * @param refundPriceTotal the value for zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setRefundPriceTotal(BigDecimal refundPriceTotal) {
        this.refundPriceTotal = refundPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.price_total
     *
     * @return the value of zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getPriceTotal() {
        return priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.price_total
     *
     * @param priceTotal the value for zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setPriceTotal(BigDecimal priceTotal) {
        this.priceTotal = priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.actual_total
     *
     * @return the value of zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getActualTotal() {
        return actualTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.actual_total
     *
     * @param actualTotal the value for zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setActualTotal(BigDecimal actualTotal) {
        this.actualTotal = actualTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.balance_status
     *
     * @return the value of zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getBalanceStatus() {
        return balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.balance_status
     *
     * @param balanceStatus the value for zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setBalanceStatus(Integer balanceStatus) {
        this.balanceStatus = balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.audit_status
     *
     * @return the value of zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.audit_status
     *
     * @param auditStatus the value for zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.create_time
     *
     * @return the value of zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.create_time
     *
     * @param createTime the value for zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.update_time
     *
     * @return the value of zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.update_time
     *
     * @param updateTime the value for zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}