package com.lile.common.mybits.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZdBalanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public ZdBalanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBalanceIdIsNull() {
            addCriterion("balance_id is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIdIsNotNull() {
            addCriterion("balance_id is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceIdEqualTo(String value) {
            addCriterion("balance_id =", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdNotEqualTo(String value) {
            addCriterion("balance_id <>", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdGreaterThan(String value) {
            addCriterion("balance_id >", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdGreaterThanOrEqualTo(String value) {
            addCriterion("balance_id >=", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdLessThan(String value) {
            addCriterion("balance_id <", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdLessThanOrEqualTo(String value) {
            addCriterion("balance_id <=", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdLike(String value) {
            addCriterion("balance_id like", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdNotLike(String value) {
            addCriterion("balance_id not like", value, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdIn(List<String> values) {
            addCriterion("balance_id in", values, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdNotIn(List<String> values) {
            addCriterion("balance_id not in", values, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdBetween(String value1, String value2) {
            addCriterion("balance_id between", value1, value2, "balanceId");
            return (Criteria) this;
        }

        public Criteria andBalanceIdNotBetween(String value1, String value2) {
            addCriterion("balance_id not between", value1, value2, "balanceId");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgIsNull() {
            addCriterion("high_level_org is null");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgIsNotNull() {
            addCriterion("high_level_org is not null");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgEqualTo(String value) {
            addCriterion("high_level_org =", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgNotEqualTo(String value) {
            addCriterion("high_level_org <>", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgGreaterThan(String value) {
            addCriterion("high_level_org >", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgGreaterThanOrEqualTo(String value) {
            addCriterion("high_level_org >=", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgLessThan(String value) {
            addCriterion("high_level_org <", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgLessThanOrEqualTo(String value) {
            addCriterion("high_level_org <=", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgLike(String value) {
            addCriterion("high_level_org like", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgNotLike(String value) {
            addCriterion("high_level_org not like", value, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgIn(List<String> values) {
            addCriterion("high_level_org in", values, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgNotIn(List<String> values) {
            addCriterion("high_level_org not in", values, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgBetween(String value1, String value2) {
            addCriterion("high_level_org between", value1, value2, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andHighLevelOrgNotBetween(String value1, String value2) {
            addCriterion("high_level_org not between", value1, value2, "highLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgIsNull() {
            addCriterion("low_level_org is null");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgIsNotNull() {
            addCriterion("low_level_org is not null");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgEqualTo(String value) {
            addCriterion("low_level_org =", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgNotEqualTo(String value) {
            addCriterion("low_level_org <>", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgGreaterThan(String value) {
            addCriterion("low_level_org >", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgGreaterThanOrEqualTo(String value) {
            addCriterion("low_level_org >=", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgLessThan(String value) {
            addCriterion("low_level_org <", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgLessThanOrEqualTo(String value) {
            addCriterion("low_level_org <=", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgLike(String value) {
            addCriterion("low_level_org like", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgNotLike(String value) {
            addCriterion("low_level_org not like", value, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgIn(List<String> values) {
            addCriterion("low_level_org in", values, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgNotIn(List<String> values) {
            addCriterion("low_level_org not in", values, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgBetween(String value1, String value2) {
            addCriterion("low_level_org between", value1, value2, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andLowLevelOrgNotBetween(String value1, String value2) {
            addCriterion("low_level_org not between", value1, value2, "lowLevelOrg");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIsNull() {
            addCriterion("semester_code is null");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIsNotNull() {
            addCriterion("semester_code is not null");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeEqualTo(String value) {
            addCriterion("semester_code =", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotEqualTo(String value) {
            addCriterion("semester_code <>", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeGreaterThan(String value) {
            addCriterion("semester_code >", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("semester_code >=", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLessThan(String value) {
            addCriterion("semester_code <", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLessThanOrEqualTo(String value) {
            addCriterion("semester_code <=", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLike(String value) {
            addCriterion("semester_code like", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotLike(String value) {
            addCriterion("semester_code not like", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIn(List<String> values) {
            addCriterion("semester_code in", values, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotIn(List<String> values) {
            addCriterion("semester_code not in", values, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeBetween(String value1, String value2) {
            addCriterion("semester_code between", value1, value2, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotBetween(String value1, String value2) {
            addCriterion("semester_code not between", value1, value2, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIsNull() {
            addCriterion("discount_rate is null");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIsNotNull() {
            addCriterion("discount_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountRateEqualTo(Integer value) {
            addCriterion("discount_rate =", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotEqualTo(Integer value) {
            addCriterion("discount_rate <>", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateGreaterThan(Integer value) {
            addCriterion("discount_rate >", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount_rate >=", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateLessThan(Integer value) {
            addCriterion("discount_rate <", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateLessThanOrEqualTo(Integer value) {
            addCriterion("discount_rate <=", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIn(List<Integer> values) {
            addCriterion("discount_rate in", values, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotIn(List<Integer> values) {
            addCriterion("discount_rate not in", values, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateBetween(Integer value1, Integer value2) {
            addCriterion("discount_rate between", value1, value2, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotBetween(Integer value1, Integer value2) {
            addCriterion("discount_rate not between", value1, value2, "discountRate");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalIsNull() {
            addCriterion("publish_price_total is null");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalIsNotNull() {
            addCriterion("publish_price_total is not null");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalEqualTo(BigDecimal value) {
            addCriterion("publish_price_total =", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalNotEqualTo(BigDecimal value) {
            addCriterion("publish_price_total <>", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalGreaterThan(BigDecimal value) {
            addCriterion("publish_price_total >", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("publish_price_total >=", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalLessThan(BigDecimal value) {
            addCriterion("publish_price_total <", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("publish_price_total <=", value, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalIn(List<BigDecimal> values) {
            addCriterion("publish_price_total in", values, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalNotIn(List<BigDecimal> values) {
            addCriterion("publish_price_total not in", values, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("publish_price_total between", value1, value2, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPublishPriceTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("publish_price_total not between", value1, value2, "publishPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalIsNull() {
            addCriterion("refund_price_total is null");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalIsNotNull() {
            addCriterion("refund_price_total is not null");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalEqualTo(BigDecimal value) {
            addCriterion("refund_price_total =", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalNotEqualTo(BigDecimal value) {
            addCriterion("refund_price_total <>", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalGreaterThan(BigDecimal value) {
            addCriterion("refund_price_total >", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_price_total >=", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalLessThan(BigDecimal value) {
            addCriterion("refund_price_total <", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_price_total <=", value, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalIn(List<BigDecimal> values) {
            addCriterion("refund_price_total in", values, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalNotIn(List<BigDecimal> values) {
            addCriterion("refund_price_total not in", values, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_price_total between", value1, value2, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andRefundPriceTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_price_total not between", value1, value2, "refundPriceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalIsNull() {
            addCriterion("price_total is null");
            return (Criteria) this;
        }

        public Criteria andPriceTotalIsNotNull() {
            addCriterion("price_total is not null");
            return (Criteria) this;
        }

        public Criteria andPriceTotalEqualTo(BigDecimal value) {
            addCriterion("price_total =", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalNotEqualTo(BigDecimal value) {
            addCriterion("price_total <>", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalGreaterThan(BigDecimal value) {
            addCriterion("price_total >", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price_total >=", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalLessThan(BigDecimal value) {
            addCriterion("price_total <", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price_total <=", value, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalIn(List<BigDecimal> values) {
            addCriterion("price_total in", values, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalNotIn(List<BigDecimal> values) {
            addCriterion("price_total not in", values, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price_total between", value1, value2, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andPriceTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price_total not between", value1, value2, "priceTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalIsNull() {
            addCriterion("actual_total is null");
            return (Criteria) this;
        }

        public Criteria andActualTotalIsNotNull() {
            addCriterion("actual_total is not null");
            return (Criteria) this;
        }

        public Criteria andActualTotalEqualTo(BigDecimal value) {
            addCriterion("actual_total =", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalNotEqualTo(BigDecimal value) {
            addCriterion("actual_total <>", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalGreaterThan(BigDecimal value) {
            addCriterion("actual_total >", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_total >=", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalLessThan(BigDecimal value) {
            addCriterion("actual_total <", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_total <=", value, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalIn(List<BigDecimal> values) {
            addCriterion("actual_total in", values, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalNotIn(List<BigDecimal> values) {
            addCriterion("actual_total not in", values, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_total between", value1, value2, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andActualTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_total not between", value1, value2, "actualTotal");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusIsNull() {
            addCriterion("balance_status is null");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusIsNotNull() {
            addCriterion("balance_status is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusEqualTo(Integer value) {
            addCriterion("balance_status =", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusNotEqualTo(Integer value) {
            addCriterion("balance_status <>", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusGreaterThan(Integer value) {
            addCriterion("balance_status >", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("balance_status >=", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusLessThan(Integer value) {
            addCriterion("balance_status <", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusLessThanOrEqualTo(Integer value) {
            addCriterion("balance_status <=", value, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusIn(List<Integer> values) {
            addCriterion("balance_status in", values, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusNotIn(List<Integer> values) {
            addCriterion("balance_status not in", values, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusBetween(Integer value1, Integer value2) {
            addCriterion("balance_status between", value1, value2, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andBalanceStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("balance_status not between", value1, value2, "balanceStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Integer> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Integer> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance
     *
     * @mbggenerated do_not_delete_during_merge Tue May 08 23:31:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_balance
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}