package com.lile.common.mybits.model;

import java.math.BigDecimal;
import java.util.Date;

public class ZdPublish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.id_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.from_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String fromOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.to_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String toOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.pulish_sn
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String pulishSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.pulish_name
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String pulishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.create_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.create_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.mayang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private BigDecimal mayang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.shiyang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private BigDecimal shiyang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.status
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.del_flag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.semester_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String semesterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.publish_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String publishType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.logistic_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String logisticType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.logistic_no
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String logisticNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.logistic_company
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String logisticCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.logistic_bag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String logisticBag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.update_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.update_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.enable_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private Byte enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_publish.remark_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.id_
     *
     * @return the value of zd_publish.id_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.id_
     *
     * @param id the value for zd_publish.id_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.org_code
     *
     * @return the value of zd_publish.org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.org_code
     *
     * @param orgCode the value for zd_publish.org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.from_org_code
     *
     * @return the value of zd_publish.from_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getFromOrgCode() {
        return fromOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.from_org_code
     *
     * @param fromOrgCode the value for zd_publish.from_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setFromOrgCode(String fromOrgCode) {
        this.fromOrgCode = fromOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.to_org_code
     *
     * @return the value of zd_publish.to_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getToOrgCode() {
        return toOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.to_org_code
     *
     * @param toOrgCode the value for zd_publish.to_org_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setToOrgCode(String toOrgCode) {
        this.toOrgCode = toOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.pulish_sn
     *
     * @return the value of zd_publish.pulish_sn
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getPulishSn() {
        return pulishSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.pulish_sn
     *
     * @param pulishSn the value for zd_publish.pulish_sn
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setPulishSn(String pulishSn) {
        this.pulishSn = pulishSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.pulish_name
     *
     * @return the value of zd_publish.pulish_name
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getPulishName() {
        return pulishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.pulish_name
     *
     * @param pulishName the value for zd_publish.pulish_name
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setPulishName(String pulishName) {
        this.pulishName = pulishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.create_by
     *
     * @return the value of zd_publish.create_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.create_by
     *
     * @param createBy the value for zd_publish.create_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.create_time
     *
     * @return the value of zd_publish.create_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.create_time
     *
     * @param createTime the value for zd_publish.create_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.mayang
     *
     * @return the value of zd_publish.mayang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public BigDecimal getMayang() {
        return mayang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.mayang
     *
     * @param mayang the value for zd_publish.mayang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setMayang(BigDecimal mayang) {
        this.mayang = mayang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.shiyang
     *
     * @return the value of zd_publish.shiyang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public BigDecimal getShiyang() {
        return shiyang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.shiyang
     *
     * @param shiyang the value for zd_publish.shiyang
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setShiyang(BigDecimal shiyang) {
        this.shiyang = shiyang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.status
     *
     * @return the value of zd_publish.status
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.status
     *
     * @param status the value for zd_publish.status
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.del_flag
     *
     * @return the value of zd_publish.del_flag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.del_flag
     *
     * @param delFlag the value for zd_publish.del_flag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.semester_code
     *
     * @return the value of zd_publish.semester_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getSemesterCode() {
        return semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.semester_code
     *
     * @param semesterCode the value for zd_publish.semester_code
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setSemesterCode(String semesterCode) {
        this.semesterCode = semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.publish_type
     *
     * @return the value of zd_publish.publish_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.publish_type
     *
     * @param publishType the value for zd_publish.publish_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setPublishType(String publishType) {
        this.publishType = publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.logistic_type
     *
     * @return the value of zd_publish.logistic_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getLogisticType() {
        return logisticType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.logistic_type
     *
     * @param logisticType the value for zd_publish.logistic_type
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setLogisticType(String logisticType) {
        this.logisticType = logisticType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.logistic_no
     *
     * @return the value of zd_publish.logistic_no
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getLogisticNo() {
        return logisticNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.logistic_no
     *
     * @param logisticNo the value for zd_publish.logistic_no
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setLogisticNo(String logisticNo) {
        this.logisticNo = logisticNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.logistic_company
     *
     * @return the value of zd_publish.logistic_company
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getLogisticCompany() {
        return logisticCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.logistic_company
     *
     * @param logisticCompany the value for zd_publish.logistic_company
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setLogisticCompany(String logisticCompany) {
        this.logisticCompany = logisticCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.logistic_bag
     *
     * @return the value of zd_publish.logistic_bag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getLogisticBag() {
        return logisticBag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.logistic_bag
     *
     * @param logisticBag the value for zd_publish.logistic_bag
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setLogisticBag(String logisticBag) {
        this.logisticBag = logisticBag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.update_by
     *
     * @return the value of zd_publish.update_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.update_by
     *
     * @param updateBy the value for zd_publish.update_by
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.update_time
     *
     * @return the value of zd_publish.update_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.update_time
     *
     * @param updateTime the value for zd_publish.update_time
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.enable_
     *
     * @return the value of zd_publish.enable_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.enable_
     *
     * @param enable the value for zd_publish.enable_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_publish.remark_
     *
     * @return the value of zd_publish.remark_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_publish.remark_
     *
     * @param remark the value for zd_publish.remark_
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}