package com.lile.common.mybits.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZdPublishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public ZdPublishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("org_code is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("org_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("org_code =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("org_code <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("org_code >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("org_code >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("org_code <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("org_code <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("org_code like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("org_code not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("org_code in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("org_code not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("org_code between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("org_code not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeIsNull() {
            addCriterion("from_org_code is null");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeIsNotNull() {
            addCriterion("from_org_code is not null");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeEqualTo(String value) {
            addCriterion("from_org_code =", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeNotEqualTo(String value) {
            addCriterion("from_org_code <>", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeGreaterThan(String value) {
            addCriterion("from_org_code >", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("from_org_code >=", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeLessThan(String value) {
            addCriterion("from_org_code <", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("from_org_code <=", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeLike(String value) {
            addCriterion("from_org_code like", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeNotLike(String value) {
            addCriterion("from_org_code not like", value, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeIn(List<String> values) {
            addCriterion("from_org_code in", values, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeNotIn(List<String> values) {
            addCriterion("from_org_code not in", values, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeBetween(String value1, String value2) {
            addCriterion("from_org_code between", value1, value2, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andFromOrgCodeNotBetween(String value1, String value2) {
            addCriterion("from_org_code not between", value1, value2, "fromOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeIsNull() {
            addCriterion("to_org_code is null");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeIsNotNull() {
            addCriterion("to_org_code is not null");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeEqualTo(String value) {
            addCriterion("to_org_code =", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeNotEqualTo(String value) {
            addCriterion("to_org_code <>", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeGreaterThan(String value) {
            addCriterion("to_org_code >", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("to_org_code >=", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeLessThan(String value) {
            addCriterion("to_org_code <", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("to_org_code <=", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeLike(String value) {
            addCriterion("to_org_code like", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeNotLike(String value) {
            addCriterion("to_org_code not like", value, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeIn(List<String> values) {
            addCriterion("to_org_code in", values, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeNotIn(List<String> values) {
            addCriterion("to_org_code not in", values, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeBetween(String value1, String value2) {
            addCriterion("to_org_code between", value1, value2, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andToOrgCodeNotBetween(String value1, String value2) {
            addCriterion("to_org_code not between", value1, value2, "toOrgCode");
            return (Criteria) this;
        }

        public Criteria andPulishSnIsNull() {
            addCriterion("pulish_sn is null");
            return (Criteria) this;
        }

        public Criteria andPulishSnIsNotNull() {
            addCriterion("pulish_sn is not null");
            return (Criteria) this;
        }

        public Criteria andPulishSnEqualTo(String value) {
            addCriterion("pulish_sn =", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnNotEqualTo(String value) {
            addCriterion("pulish_sn <>", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnGreaterThan(String value) {
            addCriterion("pulish_sn >", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnGreaterThanOrEqualTo(String value) {
            addCriterion("pulish_sn >=", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnLessThan(String value) {
            addCriterion("pulish_sn <", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnLessThanOrEqualTo(String value) {
            addCriterion("pulish_sn <=", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnLike(String value) {
            addCriterion("pulish_sn like", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnNotLike(String value) {
            addCriterion("pulish_sn not like", value, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnIn(List<String> values) {
            addCriterion("pulish_sn in", values, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnNotIn(List<String> values) {
            addCriterion("pulish_sn not in", values, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnBetween(String value1, String value2) {
            addCriterion("pulish_sn between", value1, value2, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishSnNotBetween(String value1, String value2) {
            addCriterion("pulish_sn not between", value1, value2, "pulishSn");
            return (Criteria) this;
        }

        public Criteria andPulishNameIsNull() {
            addCriterion("pulish_name is null");
            return (Criteria) this;
        }

        public Criteria andPulishNameIsNotNull() {
            addCriterion("pulish_name is not null");
            return (Criteria) this;
        }

        public Criteria andPulishNameEqualTo(String value) {
            addCriterion("pulish_name =", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameNotEqualTo(String value) {
            addCriterion("pulish_name <>", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameGreaterThan(String value) {
            addCriterion("pulish_name >", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameGreaterThanOrEqualTo(String value) {
            addCriterion("pulish_name >=", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameLessThan(String value) {
            addCriterion("pulish_name <", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameLessThanOrEqualTo(String value) {
            addCriterion("pulish_name <=", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameLike(String value) {
            addCriterion("pulish_name like", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameNotLike(String value) {
            addCriterion("pulish_name not like", value, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameIn(List<String> values) {
            addCriterion("pulish_name in", values, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameNotIn(List<String> values) {
            addCriterion("pulish_name not in", values, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameBetween(String value1, String value2) {
            addCriterion("pulish_name between", value1, value2, "pulishName");
            return (Criteria) this;
        }

        public Criteria andPulishNameNotBetween(String value1, String value2) {
            addCriterion("pulish_name not between", value1, value2, "pulishName");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andMayangIsNull() {
            addCriterion("mayang is null");
            return (Criteria) this;
        }

        public Criteria andMayangIsNotNull() {
            addCriterion("mayang is not null");
            return (Criteria) this;
        }

        public Criteria andMayangEqualTo(BigDecimal value) {
            addCriterion("mayang =", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangNotEqualTo(BigDecimal value) {
            addCriterion("mayang <>", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangGreaterThan(BigDecimal value) {
            addCriterion("mayang >", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mayang >=", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangLessThan(BigDecimal value) {
            addCriterion("mayang <", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mayang <=", value, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangIn(List<BigDecimal> values) {
            addCriterion("mayang in", values, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangNotIn(List<BigDecimal> values) {
            addCriterion("mayang not in", values, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mayang between", value1, value2, "mayang");
            return (Criteria) this;
        }

        public Criteria andMayangNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mayang not between", value1, value2, "mayang");
            return (Criteria) this;
        }

        public Criteria andShiyangIsNull() {
            addCriterion("shiyang is null");
            return (Criteria) this;
        }

        public Criteria andShiyangIsNotNull() {
            addCriterion("shiyang is not null");
            return (Criteria) this;
        }

        public Criteria andShiyangEqualTo(BigDecimal value) {
            addCriterion("shiyang =", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangNotEqualTo(BigDecimal value) {
            addCriterion("shiyang <>", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangGreaterThan(BigDecimal value) {
            addCriterion("shiyang >", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shiyang >=", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangLessThan(BigDecimal value) {
            addCriterion("shiyang <", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shiyang <=", value, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangIn(List<BigDecimal> values) {
            addCriterion("shiyang in", values, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangNotIn(List<BigDecimal> values) {
            addCriterion("shiyang not in", values, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shiyang between", value1, value2, "shiyang");
            return (Criteria) this;
        }

        public Criteria andShiyangNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shiyang not between", value1, value2, "shiyang");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIsNull() {
            addCriterion("semester_code is null");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIsNotNull() {
            addCriterion("semester_code is not null");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeEqualTo(String value) {
            addCriterion("semester_code =", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotEqualTo(String value) {
            addCriterion("semester_code <>", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeGreaterThan(String value) {
            addCriterion("semester_code >", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("semester_code >=", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLessThan(String value) {
            addCriterion("semester_code <", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLessThanOrEqualTo(String value) {
            addCriterion("semester_code <=", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeLike(String value) {
            addCriterion("semester_code like", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotLike(String value) {
            addCriterion("semester_code not like", value, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeIn(List<String> values) {
            addCriterion("semester_code in", values, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotIn(List<String> values) {
            addCriterion("semester_code not in", values, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeBetween(String value1, String value2) {
            addCriterion("semester_code between", value1, value2, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andSemesterCodeNotBetween(String value1, String value2) {
            addCriterion("semester_code not between", value1, value2, "semesterCode");
            return (Criteria) this;
        }

        public Criteria andPublishTypeIsNull() {
            addCriterion("publish_type is null");
            return (Criteria) this;
        }

        public Criteria andPublishTypeIsNotNull() {
            addCriterion("publish_type is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTypeEqualTo(String value) {
            addCriterion("publish_type =", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeNotEqualTo(String value) {
            addCriterion("publish_type <>", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeGreaterThan(String value) {
            addCriterion("publish_type >", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeGreaterThanOrEqualTo(String value) {
            addCriterion("publish_type >=", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeLessThan(String value) {
            addCriterion("publish_type <", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeLessThanOrEqualTo(String value) {
            addCriterion("publish_type <=", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeLike(String value) {
            addCriterion("publish_type like", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeNotLike(String value) {
            addCriterion("publish_type not like", value, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeIn(List<String> values) {
            addCriterion("publish_type in", values, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeNotIn(List<String> values) {
            addCriterion("publish_type not in", values, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeBetween(String value1, String value2) {
            addCriterion("publish_type between", value1, value2, "publishType");
            return (Criteria) this;
        }

        public Criteria andPublishTypeNotBetween(String value1, String value2) {
            addCriterion("publish_type not between", value1, value2, "publishType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeIsNull() {
            addCriterion("logistic_type is null");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeIsNotNull() {
            addCriterion("logistic_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeEqualTo(String value) {
            addCriterion("logistic_type =", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeNotEqualTo(String value) {
            addCriterion("logistic_type <>", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeGreaterThan(String value) {
            addCriterion("logistic_type >", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeGreaterThanOrEqualTo(String value) {
            addCriterion("logistic_type >=", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeLessThan(String value) {
            addCriterion("logistic_type <", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeLessThanOrEqualTo(String value) {
            addCriterion("logistic_type <=", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeLike(String value) {
            addCriterion("logistic_type like", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeNotLike(String value) {
            addCriterion("logistic_type not like", value, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeIn(List<String> values) {
            addCriterion("logistic_type in", values, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeNotIn(List<String> values) {
            addCriterion("logistic_type not in", values, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeBetween(String value1, String value2) {
            addCriterion("logistic_type between", value1, value2, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticTypeNotBetween(String value1, String value2) {
            addCriterion("logistic_type not between", value1, value2, "logisticType");
            return (Criteria) this;
        }

        public Criteria andLogisticNoIsNull() {
            addCriterion("logistic_no is null");
            return (Criteria) this;
        }

        public Criteria andLogisticNoIsNotNull() {
            addCriterion("logistic_no is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticNoEqualTo(String value) {
            addCriterion("logistic_no =", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoNotEqualTo(String value) {
            addCriterion("logistic_no <>", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoGreaterThan(String value) {
            addCriterion("logistic_no >", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoGreaterThanOrEqualTo(String value) {
            addCriterion("logistic_no >=", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoLessThan(String value) {
            addCriterion("logistic_no <", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoLessThanOrEqualTo(String value) {
            addCriterion("logistic_no <=", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoLike(String value) {
            addCriterion("logistic_no like", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoNotLike(String value) {
            addCriterion("logistic_no not like", value, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoIn(List<String> values) {
            addCriterion("logistic_no in", values, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoNotIn(List<String> values) {
            addCriterion("logistic_no not in", values, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoBetween(String value1, String value2) {
            addCriterion("logistic_no between", value1, value2, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticNoNotBetween(String value1, String value2) {
            addCriterion("logistic_no not between", value1, value2, "logisticNo");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyIsNull() {
            addCriterion("logistic_company is null");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyIsNotNull() {
            addCriterion("logistic_company is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyEqualTo(String value) {
            addCriterion("logistic_company =", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyNotEqualTo(String value) {
            addCriterion("logistic_company <>", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyGreaterThan(String value) {
            addCriterion("logistic_company >", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("logistic_company >=", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyLessThan(String value) {
            addCriterion("logistic_company <", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyLessThanOrEqualTo(String value) {
            addCriterion("logistic_company <=", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyLike(String value) {
            addCriterion("logistic_company like", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyNotLike(String value) {
            addCriterion("logistic_company not like", value, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyIn(List<String> values) {
            addCriterion("logistic_company in", values, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyNotIn(List<String> values) {
            addCriterion("logistic_company not in", values, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyBetween(String value1, String value2) {
            addCriterion("logistic_company between", value1, value2, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticCompanyNotBetween(String value1, String value2) {
            addCriterion("logistic_company not between", value1, value2, "logisticCompany");
            return (Criteria) this;
        }

        public Criteria andLogisticBagIsNull() {
            addCriterion("logistic_bag is null");
            return (Criteria) this;
        }

        public Criteria andLogisticBagIsNotNull() {
            addCriterion("logistic_bag is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticBagEqualTo(String value) {
            addCriterion("logistic_bag =", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagNotEqualTo(String value) {
            addCriterion("logistic_bag <>", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagGreaterThan(String value) {
            addCriterion("logistic_bag >", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagGreaterThanOrEqualTo(String value) {
            addCriterion("logistic_bag >=", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagLessThan(String value) {
            addCriterion("logistic_bag <", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagLessThanOrEqualTo(String value) {
            addCriterion("logistic_bag <=", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagLike(String value) {
            addCriterion("logistic_bag like", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagNotLike(String value) {
            addCriterion("logistic_bag not like", value, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagIn(List<String> values) {
            addCriterion("logistic_bag in", values, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagNotIn(List<String> values) {
            addCriterion("logistic_bag not in", values, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagBetween(String value1, String value2) {
            addCriterion("logistic_bag between", value1, value2, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andLogisticBagNotBetween(String value1, String value2) {
            addCriterion("logistic_bag not between", value1, value2, "logisticBag");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable_ is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable_ is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Byte value) {
            addCriterion("enable_ =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Byte value) {
            addCriterion("enable_ <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Byte value) {
            addCriterion("enable_ >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Byte value) {
            addCriterion("enable_ >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Byte value) {
            addCriterion("enable_ <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Byte value) {
            addCriterion("enable_ <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Byte> values) {
            addCriterion("enable_ in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Byte> values) {
            addCriterion("enable_ not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Byte value1, Byte value2) {
            addCriterion("enable_ between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Byte value1, Byte value2) {
            addCriterion("enable_ not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark_ is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark_ is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark_ =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark_ <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark_ >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark_ >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark_ <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark_ <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark_ like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark_ not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark_ in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark_ not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark_ between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark_ not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_publish
     *
     * @mbggenerated do_not_delete_during_merge Tue May 01 20:20:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}