package com.lile.common.mybits.persistence;

import com.lile.common.mybits.model.ZdBalanceResource;
import com.lile.common.mybits.model.ZdBalanceResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZdBalanceResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int countByExample(ZdBalanceResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int deleteByExample(ZdBalanceResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int insert(ZdBalanceResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int insertSelective(ZdBalanceResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    List<ZdBalanceResource> selectByExample(ZdBalanceResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZdBalanceResource record, @Param("example") ZdBalanceResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_balance_resource
     *
     * @mbggenerated Tue May 08 23:35:51 CST 2018
     */
    int updateByExample(@Param("record") ZdBalanceResource record, @Param("example") ZdBalanceResourceExample example);
}