package com.lile.common.mybits.persistence;

import com.lile.common.mybits.model.ZdPublish;
import com.lile.common.mybits.model.ZdPublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZdPublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int countByExample(ZdPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int deleteByExample(ZdPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int insert(ZdPublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int insertSelective(ZdPublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    List<ZdPublish> selectByExample(ZdPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    ZdPublish selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZdPublish record, @Param("example") ZdPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int updateByExample(@Param("record") ZdPublish record, @Param("example") ZdPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int updateByPrimaryKeySelective(ZdPublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_publish
     *
     * @mbggenerated Tue May 01 20:20:41 CST 2018
     */
    int updateByPrimaryKey(ZdPublish record);
}