package com.lile.common.mybits.model;

import java.time.LocalDateTime;
import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.user_id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.percent
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private Integer percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_cover
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private String bookCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.introduction
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.status
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.user_id
     *
     * @return the value of book.user_id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.user_id
     *
     * @param userId the value for book.user_id
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.percent
     *
     * @return the value of book.percent
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public Integer getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.percent
     *
     * @param percent the value for book.percent
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_cover
     *
     * @return the value of book.book_cover
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public String getBookCover() {
        return bookCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_cover
     *
     * @param bookCover the value for book.book_cover
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setBookCover(String bookCover) {
        this.bookCover = bookCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.introduction
     *
     * @return the value of book.introduction
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.introduction
     *
     * @param introduction the value for book.introduction
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.status
     *
     * @return the value of book.status
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.status
     *
     * @param status the value for book.status
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbggenerated Wed Jan 01 18:50:29 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}