package com.lile.common.mybits.model;

import java.util.Date;

public class Todo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.user_id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.title
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.content
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.status
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.create_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.update_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.user_id
     *
     * @return the value of todo.user_id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.user_id
     *
     * @param userId the value for todo.user_id
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.title
     *
     * @return the value of todo.title
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.title
     *
     * @param title the value for todo.title
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.content
     *
     * @return the value of todo.content
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.content
     *
     * @param content the value for todo.content
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.status
     *
     * @return the value of todo.status
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.status
     *
     * @param status the value for todo.status
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.create_time
     *
     * @return the value of todo.create_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.create_time
     *
     * @param createTime the value for todo.create_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.update_time
     *
     * @return the value of todo.update_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.update_time
     *
     * @param updateTime the value for todo.update_time
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}