package com.lile.common.mybits.persistence;

import com.lile.common.mybits.model.Todo;
import com.lile.common.mybits.model.TodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    Todo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Jan 01 11:36:11 CST 2020
     */
    int updateByPrimaryKey(Todo record);
}